module.exports = {
    admin: require('./admin'),
    // customer: require('./customer'),
    // driver: require('./driver'),
    otp: require('./otp'),
    // bank: require('./bank'),
    // otpDriver: require('./otpDriver'),
    upload: require('./fileUpload'),
    // deliveryAddress: require('./deliveryAddress'),
    // fuelCategory: require('./fuelcategory'),
    // fuelProduct: require('./fuelproduct'),
    // contactForm: require('./contactForm'),
    // booking: require('./booking'),
    // vehicleCategory: require('./vehicleCategory'),
    // vehicle: require('./vehicle'),
    // notification: require('./notification'),
    // wallet: require("./wallet"),
    // card: require('./card'),
    // promo: require("./promo")
}